name: speechBCI_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7  # Adjust the Python version as needed
  - tensorflow-gpu=2.7.0
  - hydra-core=1.3.2
  - hydra-submitit-launcher=1.1.5
  - hydra-optuna-sweeper=1.2.0
  - transformers=4.28.1
  - redis
  - seaborn=0.12.2
  - pandas
  - ipywidgets
  - tqdm
  - g2p_en=2.1.0
  - numpy=1.25.0
  - scipy=1.11.1
  - pytorch=1.13.1  # Note: 'torch' is named 'pytorch' in conda
  - accelerate=0.20.3
  - bitsandbytes=0.39.1
  - edit_distance=1.0.6
  - wandb=0.15.5
  - hiplot
  - numba
  - scikit-learn
  - pip:
    - bitsandbytes==0.39.1  # Some packages might be available only via pip
    - edit_distance==1.0.6
    - g2p_en==2.1.0
    - wandb==0.15.5
    - accelerate==0.20.3
